#include "scripting/global_binder.h"
#include "utils/debug.h"
#include "utils/screen.h"
#include "utils/time.h"
#include "utils/engine.h"
#include "control/key_code.h"
#include "control/input.h"

void LuaGlobalBinder::binding(sol::state& sol_state_)
{
	auto cpp_ns_table = sol_state_["Cpp"].get_or_create<sol::table>();

	// Utils
	cpp_ns_table.new_usertype<Engine>("Engine",
		"Init", &Engine::Init,
		"Run", &Engine::Run,
		"UpdateScreenSize", &Engine::UpdateScreenSize,
		"LogicTick", &Engine::LogicTick,
		"RenderTick", &Engine::RenderTick,
		"ShutDown", &Engine::ShutDown
	);

	cpp_ns_table.new_usertype<LogSystem>("LogSystem", sol::call_constructor, sol::constructors<LogSystem()>()
	);

	cpp_ns_table.new_usertype<Screen>("Screen",
		"width", &Screen::width,
		"height", &Screen::height,
		"aspect_ratio", &Screen::aspect_ratio,
		"set_width", &Screen::set_width,
		"set_height", &Screen::set_height,
		"set_width_height", &Screen::set_width_height
	);

	cpp_ns_table.new_usertype<Time>("Time",
		"Init", &Time::Init,
		"Update", &Time::Update,
		"TimeSinceStartup", &Time::TimeSinceStartup,
		"delta_time", &Time::delta_time
	);

	// Control
	cpp_ns_table.new_usertype<Input>("Input",
		"RecordKey", &Input::RecordKey,
		"GetKey", &Input::GetKey,
		"GetKeyDown", &Input::GetKeyDown,
		"GetKeyUp", &Input::GetKeyUp,
		"Update", &Input::Update,
		"GetMouseButton", &Input::GetMouseButton,
		"GetMouseButtonDown", &Input::GetMouseButtonDown,
		"GetMouseButtonUp", &Input::GetMouseButtonUp,
		"mousePosition", &Input::mousePosition,
		"set_mousePosition", &Input::set_mousePosition,
		"mouse_scroll", &Input::mouse_scroll,
		"RecordScroll", &Input::RecordScroll
	);

	/*cpp_ns_table.new_enum<KeyAction, true>("KeyAction", {
			{"KEY_ACTION_UP",KeyAction::KEY_ACTION_UP},
			{"KEY_ACTION_DOWN",KeyAction::KEY_ACTION_DOWN},
			{"KEY_ACTION_REPEAT",KeyAction::KEY_ACTION_REPEAT}
		});

	cpp_ns_table.new_enum<KeyCode, true>("KeyCode", {
		{"KEY_CODE_UNKNOWN",KeyCode::KEY_CODE_UNKNOWN},
		{"MOUSE_BUTTON_1",KeyCode::MOUSE_BUTTON_1},
		{"MOUSE_BUTTON_2",KeyCode::MOUSE_BUTTON_2},
		{"MOUSE_BUTTON_3",KeyCode::MOUSE_BUTTON_3},
		{"MOUSE_BUTTON_4",KeyCode::MOUSE_BUTTON_4},
		{"MOUSE_BUTTON_5",KeyCode::MOUSE_BUTTON_5},
		{"MOUSE_BUTTON_6",KeyCode::MOUSE_BUTTON_6},
		{"MOUSE_BUTTON_7",KeyCode::MOUSE_BUTTON_7},
		{"MOUSE_BUTTON_8",KeyCode::MOUSE_BUTTON_8},
		{"MOUSE_BUTTON_LAST",KeyCode::MOUSE_BUTTON_LAST},
		{"MOUSE_BUTTON_LEFT",KeyCode::MOUSE_BUTTON_LEFT},
		{"MOUSE_BUTTON_RIGHT",KeyCode::MOUSE_BUTTON_RIGHT},
		{"MOUSE_BUTTON_MIDDLE",KeyCode::MOUSE_BUTTON_MIDDLE},
		{"KEY_CODE_SPACE",KeyCode::KEY_CODE_SPACE},
		{"KEY_CODE_APOSTROPHE",KeyCode::KEY_CODE_APOSTROPHE},
		{"KEY_CODE_COMMA",KeyCode::KEY_CODE_COMMA},
		{"KEY_CODE_MINUS",KeyCode::KEY_CODE_MINUS},
		{"KEY_CODE_PERIOD",KeyCode::KEY_CODE_PERIOD},
		{"KEY_CODE_SLASH",KeyCode::KEY_CODE_SLASH},
		{"KEY_CODE_0",KeyCode::KEY_CODE_0},
		{"KEY_CODE_1",KeyCode::KEY_CODE_1},
		{"KEY_CODE_2",KeyCode::KEY_CODE_2},
		{"KEY_CODE_3",KeyCode::KEY_CODE_3},
		{"KEY_CODE_4",KeyCode::KEY_CODE_4},
		{"KEY_CODE_5",KeyCode::KEY_CODE_5},
		{"KEY_CODE_6",KeyCode::KEY_CODE_6},
		{"KEY_CODE_7",KeyCode::KEY_CODE_7},
		{"KEY_CODE_8",KeyCode::KEY_CODE_8},
		{"KEY_CODE_9",KeyCode::KEY_CODE_9},
		{"KEY_CODE_SEMICOLON",KeyCode::KEY_CODE_SEMICOLON},
		{"KEY_CODE_EQUAL",KeyCode::KEY_CODE_EQUAL},
		{"KEY_CODE_A",KeyCode::KEY_CODE_A},
		{"KEY_CODE_B",KeyCode::KEY_CODE_B},
		{"KEY_CODE_C",KeyCode::KEY_CODE_C},
		{"KEY_CODE_D",KeyCode::KEY_CODE_D},
		{"KEY_CODE_E",KeyCode::KEY_CODE_E},
		{"KEY_CODE_F",KeyCode::KEY_CODE_F},
		{"KEY_CODE_G",KeyCode::KEY_CODE_G},
		{"KEY_CODE_H",KeyCode::KEY_CODE_H},
		{"KEY_CODE_I",KeyCode::KEY_CODE_I},
		{"KEY_CODE_J",KeyCode::KEY_CODE_J},
		{"KEY_CODE_K",KeyCode::KEY_CODE_K},
		{"KEY_CODE_L",KeyCode::KEY_CODE_L},
		{"KEY_CODE_M",KeyCode::KEY_CODE_M},
		{"KEY_CODE_N",KeyCode::KEY_CODE_N},
		{"KEY_CODE_O",KeyCode::KEY_CODE_O},
		{"KEY_CODE_P",KeyCode::KEY_CODE_P},
		{"KEY_CODE_Q",KeyCode::KEY_CODE_Q},
		{"KEY_CODE_R",KeyCode::KEY_CODE_R},
		{"KEY_CODE_S",KeyCode::KEY_CODE_S},
		{"KEY_CODE_T",KeyCode::KEY_CODE_T},
		{"KEY_CODE_U",KeyCode::KEY_CODE_U},
		{"KEY_CODE_V",KeyCode::KEY_CODE_V},
		{"KEY_CODE_W",KeyCode::KEY_CODE_W},
		{"KEY_CODE_X",KeyCode::KEY_CODE_X},
		{"KEY_CODE_Y",KeyCode::KEY_CODE_Y},
		{"KEY_CODE_Z",KeyCode::KEY_CODE_Z},
		{"KEY_CODE_LEFT_BRACKET",KeyCode::KEY_CODE_LEFT_BRACKET},
		{"KEY_CODE_BACKSLASH", KeyCode::KEY_CODE_BACKSLASH},
		{ "KEY_CODE_RIGHT_BRACKET",KeyCode::KEY_CODE_RIGHT_BRACKET },
		{ "KEY_CODE_GRAVE_ACCENT",KeyCode::KEY_CODE_GRAVE_ACCENT },
		{ "KEY_CODE_WORLD_1",KeyCode::KEY_CODE_WORLD_1 },
		{ "KEY_CODE_WORLD_2",KeyCode::KEY_CODE_WORLD_2 },
		{ "KEY_CODE_ESCAPE",KeyCode::KEY_CODE_ESCAPE },
		{ "KEY_CODE_ENTER",KeyCode::KEY_CODE_ENTER },
		{ "KEY_CODE_TAB",KeyCode::KEY_CODE_TAB },
		{ "KEY_CODE_BACKSPACE",KeyCode::KEY_CODE_BACKSPACE },
		{ "KEY_CODE_INSERT",KeyCode::KEY_CODE_INSERT },
		{ "KEY_CODE_DELETE",KeyCode::KEY_CODE_DELETE },
		{ "KEY_CODE_RIGHT",KeyCode::KEY_CODE_RIGHT },
		{ "KEY_CODE_LEFT",KeyCode::KEY_CODE_LEFT },
		{ "KEY_CODE_DOWN",KeyCode::KEY_CODE_DOWN },
		{ "KEY_CODE_UP",KeyCode::KEY_CODE_UP },
		{ "KEY_CODE_PAGE_UP",KeyCode::KEY_CODE_PAGE_UP },
		{ "KEY_CODE_PAGE_DOWN",KeyCode::KEY_CODE_PAGE_DOWN },
		{ "KEY_CODE_HOME",KeyCode::KEY_CODE_HOME },
		{ "KEY_CODE_END",KeyCode::KEY_CODE_END },
		{ "KEY_CODE_CAPS_LOCK",KeyCode::KEY_CODE_CAPS_LOCK },
		{ "KEY_CODE_SCROLL_LOCK",KeyCode::KEY_CODE_SCROLL_LOCK },
		{ "KEY_CODE_NUM_LOCK",KeyCode::KEY_CODE_NUM_LOCK },
		{ "KEY_CODE_PRINT_SCREEN",KeyCode::KEY_CODE_PRINT_SCREEN },
		{ "KEY_CODE_PAUSE",KeyCode::KEY_CODE_PAUSE },
		{ "KEY_CODE_F1",KeyCode::KEY_CODE_F1 },
		{ "KEY_CODE_F2",KeyCode::KEY_CODE_F2 },
		{ "KEY_CODE_F3",KeyCode::KEY_CODE_F3 },
		{ "KEY_CODE_F4",KeyCode::KEY_CODE_F4 },
		{ "KEY_CODE_F5",KeyCode::KEY_CODE_F5 },
		{ "KEY_CODE_F6",KeyCode::KEY_CODE_F6 },
		{ "KEY_CODE_F7",KeyCode::KEY_CODE_F7 },
		{ "KEY_CODE_F8",KeyCode::KEY_CODE_F8 },
		{ "KEY_CODE_F9",KeyCode::KEY_CODE_F9 },
		{ "KEY_CODE_F10",KeyCode::KEY_CODE_F10 },
		{ "KEY_CODE_F11",KeyCode::KEY_CODE_F11 },
		{ "KEY_CODE_F12",KeyCode::KEY_CODE_F12 },
		{ "KEY_CODE_F13",KeyCode::KEY_CODE_F13 },
		{ "KEY_CODE_F14",KeyCode::KEY_CODE_F14 },
		{ "KEY_CODE_F15",KeyCode::KEY_CODE_F15 },
		{ "KEY_CODE_F16",KeyCode::KEY_CODE_F16 },
		{ "KEY_CODE_F17",KeyCode::KEY_CODE_F17 },
		{ "KEY_CODE_F18",KeyCode::KEY_CODE_F18 },
		{ "KEY_CODE_F19",KeyCode::KEY_CODE_F19 },
		{ "KEY_CODE_F20",KeyCode::KEY_CODE_F20 },
		{ "KEY_CODE_F21",KeyCode::KEY_CODE_F21 },
		{ "KEY_CODE_F22",KeyCode::KEY_CODE_F22 },
		{ "KEY_CODE_F23",KeyCode::KEY_CODE_F23 },
		{ "KEY_CODE_F24",KeyCode::KEY_CODE_F24 },
		{ "KEY_CODE_F25",KeyCode::KEY_CODE_F25 },
		{ "KEY_CODE_KP_0",KeyCode::KEY_CODE_KP_0 },
		{ "KEY_CODE_KP_1",KeyCode::KEY_CODE_KP_1 },
		{ "KEY_CODE_KP_2",KeyCode::KEY_CODE_KP_2 },
		{ "KEY_CODE_KP_3",KeyCode::KEY_CODE_KP_3 },
		{ "KEY_CODE_KP_4",KeyCode::KEY_CODE_KP_4 },
		{ "KEY_CODE_KP_5",KeyCode::KEY_CODE_KP_5 },
		{ "KEY_CODE_KP_6",KeyCode::KEY_CODE_KP_6 },
		{ "KEY_CODE_KP_7",KeyCode::KEY_CODE_KP_7 },
		{ "KEY_CODE_KP_8",KeyCode::KEY_CODE_KP_8 },
		{ "KEY_CODE_KP_9",KeyCode::KEY_CODE_KP_9 },
		{ "KEY_CODE_KP_DECIMAL",KeyCode::KEY_CODE_KP_DECIMAL },
		{ "KEY_CODE_KP_DIVIDE",KeyCode::KEY_CODE_KP_DIVIDE },
		{ "KEY_CODE_KP_MULTIPLY",KeyCode::KEY_CODE_KP_MULTIPLY },
		{ "KEY_CODE_KP_SUBTRACT",KeyCode::KEY_CODE_KP_SUBTRACT },
		{ "KEY_CODE_KP_ADD",KeyCode::KEY_CODE_KP_ADD },
		{ "KEY_CODE_KP_ENTER",KeyCode::KEY_CODE_KP_ENTER },
		{ "KEY_CODE_KP_EQUAL",KeyCode::KEY_CODE_KP_EQUAL },
		{ "KEY_CODE_LEFT_SHIFT",KeyCode::KEY_CODE_LEFT_SHIFT },
		{ "KEY_CODE_LEFT_CONTROL",KeyCode::KEY_CODE_LEFT_CONTROL },
		{ "KEY_CODE_LEFT_ALT",KeyCode::KEY_CODE_LEFT_ALT },
		{ "KEY_CODE_LEFT_SUPER",KeyCode::KEY_CODE_LEFT_SUPER },
		{ "KEY_CODE_RIGHT_SHIFT",KeyCode::KEY_CODE_RIGHT_SHIFT },
		{ "KEY_CODE_RIGHT_CONTROL",KeyCode::KEY_CODE_RIGHT_CONTROL },
		{ "KEY_CODE_RIGHT_ALT",KeyCode::KEY_CODE_RIGHT_ALT },
		{ "KEY_CODE_RIGHT_SUPER",KeyCode::KEY_CODE_RIGHT_SUPER },
		{ "KEY_CODE_MENU",KeyCode::KEY_CODE_MENU }
	});*/
	
}
